use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use ignore::WalkBuilder;

/// Walk the given paths, returning every file that should be linted.
/// Honors `.gitignore`, `.ignore`, and hidden-file rules of the `ignore` crate
/// (matching `ripgrep` semantics).
pub fn collect_files(roots: &[PathBuf]) -> Result<Vec<PathBuf>> {
  let mut files = Vec::new();

  for root in roots {
    if !root.exists() {
      anyhow::bail!("path does not exist: {}", root.display());
    }

    if root.is_file() {
      files.push(root.clone());
      continue;
    }

    let mut builder = WalkBuilder::new(root);
    // Standard ignore behavior — same as `rg`.
    builder
      .hidden(true)
      .git_ignore(true)
      .git_exclude(true)
      .git_global(true)
      .parents(true)
      .follow_links(false);

    for entry in builder.build() {
      let entry =
        entry.with_context(|| format!("walking {}", root.display()))?;
      if entry.file_type().is_some_and(|t| t.is_file()) {
        let path = entry.into_path();
        if should_lint(&path) {
          files.push(path);
        }
      }
    }
  }

  files.sort();
  files.dedup();
  Ok(files)
}

/// Filter out binary, generated, or obviously-uninteresting paths.
fn should_lint(path: &Path) -> bool {
  if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
    // Lock files are autogenerated.
    if matches!(
      name,
      "Cargo.lock"
        | "package-lock.json"
        | "yarn.lock"
        | "pnpm-lock.yaml"
        | "poetry.lock"
        | "uv.lock"
        | "Gemfile.lock"
        | "composer.lock"
    ) {
      return false;
    }
  }

  if let Some(ext) = path.extension().and_then(|e| e.to_str())
    && is_binary_extension(ext)
  {
    return false;
  }

  true
}

fn is_binary_extension(ext: &str) -> bool {
  matches!(
    ext.to_ascii_lowercase().as_str(),
    // Images
    "png" | "jpg" | "jpeg" | "gif" | "bmp" | "ico" | "webp" | "tiff" | "svg" |
        // Audio / video
        "mp3" | "mp4" | "wav" | "ogg" | "flac" | "mov" | "avi" | "mkv" | "webm" |
        // Archives
        "zip" | "tar" | "gz" | "tgz" | "bz2" | "xz" | "7z" | "rar" | "zst" |
        // Compiled / binary blobs
        "exe" | "dll" | "so" | "dylib" | "a" | "o" | "obj" | "class" | "wasm" |
        "pyc" | "pyo" | "pdb" | "rlib" |
        // Documents (binary)
        "pdf" | "doc" | "docx" | "xls" | "xlsx" | "ppt" | "pptx" |
        // Fonts
        "ttf" | "otf" | "woff" | "woff2" | "eot" |
        // Databases
        "db" | "sqlite" | "sqlite3"
  )
}

#[cfg(test)]
mod tests {
  use super::*;
  use std::fs;
  use tempfile::tempdir;

  #[test]
  fn skips_lockfiles_and_binaries() {
    assert!(!should_lint(Path::new("Cargo.lock")));
    assert!(!should_lint(Path::new("foo/package-lock.json")));
    assert!(!should_lint(Path::new("img.png")));
    assert!(!should_lint(Path::new("dist/app.WASM"))); // case-insensitive
    assert!(should_lint(Path::new("src/main.rs")));
    assert!(should_lint(Path::new("README"))); // no extension
  }

  #[test]
  fn collect_includes_regular_files() {
    let dir = tempdir().unwrap();
    fs::write(dir.path().join("a.txt"), "hi\n").unwrap();
    fs::write(dir.path().join("b.rs"), "fn x() {}\n").unwrap();
    let mut files = collect_files(&[dir.path().to_path_buf()]).unwrap();
    files.sort();
    assert_eq!(files.len(), 2);
    assert!(files[0].ends_with("a.txt"));
    assert!(files[1].ends_with("b.rs"));
  }

  #[test]
  fn collect_respects_gitignore() {
    let dir = tempdir().unwrap();
    // `ignore::WalkBuilder` only applies `.gitignore` rules inside
    // a git repository, so initialize one.
    fs::create_dir(dir.path().join(".git")).unwrap();
    fs::write(dir.path().join(".gitignore"), "secret.txt\n").unwrap();
    fs::write(dir.path().join("ok.txt"), "ok\n").unwrap();
    fs::write(dir.path().join("secret.txt"), "shh\n").unwrap();

    let files = collect_files(&[dir.path().to_path_buf()]).unwrap();
    let names: Vec<_> = files
      .iter()
      .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
      .collect();
    assert!(names.contains(&"ok.txt".to_string()));
    assert!(!names.contains(&"secret.txt".to_string()));
  }

  #[test]
  fn single_file_path_is_returned_directly() {
    let dir = tempdir().unwrap();
    let file = dir.path().join("only.txt");
    fs::write(&file, "x\n").unwrap();
    let files = collect_files(&[file.clone()]).unwrap();
    assert_eq!(files, vec![file]);
  }

  #[test]
  fn missing_path_errors() {
    let err = collect_files(&[PathBuf::from("/definitely/does/not/exist")])
      .unwrap_err();
    assert!(err.to_string().contains("does not exist"));
  }
}
